### ISSUE TITLE
Wrong path to docker image bag database in docker compose example

### ISSUE THREAD

**Issue by mazwingel** [swri-robotics/bag-database#119]
The example docker-compose.yaml for "Without Authentication" and "With LDAP Authentication" in the documentation reference "swri-robotics/bag-database:latest" as image for bagdb, which can't be found. "swrirobotics/bag-database:latest" can be found and works out of the box.

**Comment by pjreed** [comment]
Oops, thanks for the catch.  I always forget that Dockerhub doesn't allow dashes in organization names.  I'll fix that, plus a couple other places where it looks like I missed it.
