### ISSUE TITLE
BDB scripts do not work if there are the same name among the argument bags

### ISSUE THREAD

**Issue by anatolykabakov** [swri-robotics/bag-database#130]
Playback:

1. select two bags with the same names in the List View, for example, 1_450_1.bag and 1_450_1.bag
2. select process bag with script from the context menu
3. when the script finishes, judging by the status bar, no new results will appear in the scripts window

This is most likely due to the fact that /path/to/bagname.bag is mounted in docker as /bagname.bag.

**Comment by pjreed** [comment]
Good catch, I had never tried having multiple bags with the same name.  I should be able to fix that by adding the path to the mount point inside the Docker container.
