### ISSUE TITLE
Is bag database or one of its dependencies affected by log4j vulnerability?

### ISSUE THREAD

**Issue by AndreasR30** [swri-robotics/bag-database#167]
Hello,

do you think bag database or any of its dependencies is affected by recent log4j vulnerability?

Thank you very much

**Comment by pjreed** [comment]
No, the bag database uses logback as its logging mechanism, which is unaffected by log4j's vulnerabilities (http://logback.qos.ch/).

**Comment by danthony06** [comment]
Correct, we are unaffected by the log4j vulnerability.

**Comment by AndreasR30** [comment]
That are great news. Thank you very much.
