### ISSUE TITLE
ROS2

### ISSUE THREAD

**Issue by DavidSku** [swri-robotics/bag-database#168]
Hello,
I have a short question. Does the database also work with ROS2 rosbags?

Thanks in advance.

David

**Comment by danthony06** [comment]
Sorry, at the current time ROS 2 bags only hold the CDR serialized
messages, and do not contain the informative needed to deserialize them. We
would have to have a method of rebuilding the entire system environment to
introspect them. This is supposed to change in the upcoming H release of
ROS 2, so hopefully soon we can support them.
