### ISSUE TITLE
when open with webviz, sometimes the bag during severe reduction

### ISSUE THREAD

**Issue by 123dbl** [swri-robotics/bag-database#192]
the bag duration in bag-database is 70 secs
![bag-database](https://user-images.githubusercontent.com/31713914/172807037-562fcb20-09c1-4f08-972b-9977ca80b210.png)
but the webviz only show 35 secs data
![webviz](https://user-images.githubusercontent.com/31713914/172806970-7a768740-fdd0-4eb0-9ff7-b491304db0e7.png)

have anybody else encountered the problem?

**Comment by danthony06** [comment]
I haven't seen this. I suspected the bag database is using the bag's metadata to determine the bag length, and webviz is using the timestamps in the recorded messages.
