### ISSUE TITLE
Show video streams for image topics

### ISSUE THREAD

**Issue by pjreed** [swri-robotics/bag-database#26]
Currently it's possible to display the first image on a topic, but it'd be really handy to be able to stream the topic as a video.

**Comment by fabolhak** [comment]
I'm wondering if it is possible to create this videos on demand (when the user clicks on the icon) or if they should be preprocessed. Unfortunately my Java experience is very little. So I can't tell what is feasible.


Additionally we made some good experience with "time-lapsing" the videos (e.g. showing 1 frame per second). This gives the user a faster overview what’s going on in the bag. Maybe the time lapse effect can be controlled via a parameter?

**Comment by pjreed** [comment]
How feasible it is to create videos on demand may depend on the resolution and frame rate of the image topic.  I think that at least 720p at 30 fps should be possible on any modern CPU.  Random access of data in bag files is very slow, but reading data sequentially is pretty fast, so it's just a matter of figuring out how to encode the images into a video stream and return it to the user.  I'm not familiar with any Java video encoding libraries, so it's just a matter of me finding a good one and figuring out how to use it.
