### ISSUE TITLE
"Copy Link" from Folder View puts bag path instead of id in the URL

### ISSUE THREAD

**Issue by pjreed** [swri-robotics/bag-database#56]
The endpoint used to download bag files expects to be passed a database ID.  The "Copy Link" context menu item in the List View puts the id in there as expected, but the Folder View puts the full path to the bag in there, which won't work at all.

**Comment by alan707** [comment]
@pjreed it seems like this issue is still present.  I submitted a PR that should fix it: https://github.com/swri-robotics/bag-database/pull/85
