### ISSUE TITLE
entrypoint.sh perl: command not found

### ISSUE THREAD

**Issue by djchopp** [swri-robotics/bag-database#98]
While starting up the bagdb in docker I receive 3 failed commands in entrypoint.sh:

```
/entrypoint.sh: line 12: perl: command not found
/entrypoint.sh: line 13: perl: command not found
/entrypoint.sh: line 14: perl: command not found
```

Which matches these lines in entrpoint.sh:

```
VEHICLE_NAME_TOPICS='['`echo ${VEHICLE_NAME_TOPICS} | perl -pe 's#([/\w+]+)#"\1"#g'`']'
METADATA_TOPICS='['`echo ${METADATA_TOPICS} | perl -pe 's#([/\w+]+)#"\1"#g'`']'
GPS_TOPICS='['`echo ${GPS_TOPICS} | perl -pe 's#([/\w+]+)#"\1"#g'`']'
```

I do not see perl as a direct dependency in the dockerfile. Should it be part of the apt-get in the dockerfile?

run on fresh install of ubuntu 18.04 x64 server + docker.io

**Comment by pjreed** [comment]
Interesting, I wonder if the base image it's building on changed at some point and removed perl; it definitely should be there.
